import{classifyEntries,sumMonth,limitStatus,wageEstimate,fmtMinutes,addMonths,statutoryBreakSuggestionMinutes,companyBreakSuggestionMinutes}from'./logic.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pad=n=>String(n).padStart(2,'0'),dateKey=(d=new Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,timeKey=(d=new Date)=>`${pad(d.getHours())}:${pad(d.getMinutes())}`,today=()=>dateKey(),curMonth=()=>today().slice(0,7),yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Math.round(n||0));
const DEF={baseSalary:0,wageBaseMonthly:0,avgMonthlyScheduledHours:160,dailyLegalHours:8,weeklyLegalHours:40,agreementStartMonth:4,weekStartsMonday:true,disasterRestoration:false};
let db,entries=[],settings={...DEF},payslips={},selected=null;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('zangyo36_db',1);r.onupgradeneeded=()=>{let d=r.result;for(const [n,k]of[['entries','id'],['settings','key'],['payslips','month']])if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:k})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function all(s){return new Promise((res,rej)=>{let r=db.transaction(s).objectStore(s).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(s,v){return new Promise((res,rej)=>{mark('保存中','warn');let r=db.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>{mark('保存済み','ok');res()};r.onerror=()=>rej(r.error)})}
function del(s,k){return new Promise((res,rej)=>{let r=db.transaction(s,'readwrite').objectStore(s).delete(k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clear(s){return new Promise((res,rej)=>{let r=db.transaction(s,'readwrite').objectStore(s).clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function mark(t,c){$('#saveState').textContent=t;$('#saveState').className='status '+c}
function classified(){return classifyEntries(entries,settings)}
function rows(d){return entries.filter(e=>e.date===d).sort((a,b)=>(a.createdAt||'').localeCompare(b.createdAt||''))}
function dayEntry(d){let a=rows(d);return a.find(e=>e.start&&!e.end)||a.at(-1)||null}
function openEntry(){return entries.filter(e=>e.start&&!e.end).sort((a,b)=>(a.createdAt||'').localeCompare(b.createdAt||'')).at(-1)||null}
function fmtDate(k){let d=new Date(k+'T12:00:00'),w='日月火水木金土'[d.getDay()];return`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日（${w}）`}
function clock(){let n=new Date;$('#todayDate').textContent=fmtDate(dateKey(n));$('#liveClock').textContent=`${pad(n.getHours())}:${pad(n.getMinutes())}:${pad(n.getSeconds())}`}
function monthOpts(el){el.innerHTML='';for(let i=-14;i<=3;i++){let k=addMonths(curMonth(),i),o=new Option(k.replace('-','年')+'月',k,k===curMonth(),k===curMonth());el.add(o)}}
function initOpts(){monthOpts($('#monthlyMonth'));monthOpts($('#wageMonth'));for(let m=1;m<=12;m++)$('#agreementStartMonth').add(new Option(m+'月',m))}
function tab(n){$$('.tabbtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===n));$$('.tab').forEach(x=>x.classList.toggle('active',x.id==='tab-'+n));if(n==='monthly')renderMonth();if(n==='wage')renderWage()}
function renderToday(){let c=classified(),st=limitStatus(c,curMonth(),settings),m=st.current,t=dayEntry(today()),o=openEntry();$('#mOt').textContent=fmtMinutes(m.ot);$('#mHoliday').textContent=fmtMinutes(m.holiday);$('#mCombined').textContent=fmtMinutes(m.combined);$('#mOver45').textContent=`${st.over45Count}/6`;$('#remaining').textContent=fmtMinutes(st.tightest.minutes);$('#remainingReason').textContent='制約：'+st.tightest.label;$('#clockInTime').textContent=t?.start||'未打刻';$('#clockOutTime').textContent=t?.end||((o&&o.date!==today())?'夜勤継続中':'未打刻');let b=$('#breachBox');b.classList.toggle('hidden',!st.breaches.length);if(st.breaches.length)b.innerHTML='<strong>要確認</strong><br>'+st.breaches.join('<br>');let n=$('#activeShiftNotice');n.classList.toggle('hidden',!(o&&o.date!==today()));if(o&&o.date!==today())n.textContent=`${fmtDate(o.date)} ${o.start} から勤務中です。`}
async function punch(type){let n=new Date,d=dateKey(n),t=timeKey(n);if(type==='in'){if(openEntry())return msg('勤務中です。先に退勤してください。');let e=dayEntry(d);if(e?.start)return msg(`本日の出勤は ${e.start} に打刻済みです。`);e=e||{id:uid(),date:d,createdAt:n.toISOString(),breakMinutes:0,nightBreakMinutes:0,isLegalHoliday:false,memo:''};if(!entries.includes(e))entries.push(e);e.start=t;e.punchInAt=n.toISOString();await put('entries',e);msg(`出勤 ${t} を保存しました。`)}else{let e=openEntry()||dayEntry(d);if(!e?.start)return msg('先に出勤を打刻してください。');if(e.end)return msg(`退勤は ${e.end} に打刻済みです。`);e.end=t;e.punchOutAt=n.toISOString();e.breakMinutes=companyBreakSuggestionMinutes(e.start,e.end);await put('entries',e);msg(`退勤 ${t} を保存しました。休憩 ${e.breakMinutes}分を自動設定しました。`)}render()}
function msg(s){$('#todayPunchMessage').textContent=s}
function hold(btn,type){let tm;const off=()=>{clearTimeout(tm);btn.classList.remove('holding')};btn.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();btn.classList.add('holding');tm=setTimeout(()=>{off();punch(type)},800)};btn.onpointerup=btn.onpointerleave=btn.onpointercancel=off;btn.oncontextmenu=e=>e.preventDefault();btn.onclick=e=>{e.preventDefault();msg('約0.8秒長押ししてください。')}}
function dim(k){let[y,m]=k.split('-').map(Number);return new Date(y,m,0).getDate()}
function aggregate(c,d){let r=c.filter(x=>x.date===d);if(!r.length)return null;return{work:r.reduce((s,x)=>s+x.calc.workMinutes,0),ot:r.reduce((s,x)=>s+x.calc.overtimeMinutes,0),deep:r.reduce((s,x)=>s+x.calc.deepOvertimeMinutes+x.calc.scheduledDeepMinutes+x.calc.legalHolidayDeepMinutes,0),holiday:r.reduce((s,x)=>s+x.calc.legalHolidayMinutes,0)}}
function renderMonth(){let c=classified(),k=$('#monthlyMonth').value||curMonth(),st=limitStatus(c,k,settings),m=st.current;$('#periodText').textContent=`${st.period.months[0]} ～ ${st.period.months[11]}`;$('#sOt').textContent=fmtMinutes(m.ot);$('#sCombined').textContent=fmtMinutes(m.combined);$('#sAnnual').textContent=fmtMinutes(st.annualOT);$('#sCount').textContent=`${st.over45Count}/6`;let[y,mo]=k.split('-').map(Number),h='';for(let d=1;d<=31;d++){if(d>dim(k)){h+=`<tr class="invalid-day"><td>${d}</td><td>—</td><td colspan="6">この月にはありません</td></tr>`;continue}let dk=`${k}-${pad(d)}`,a=aggregate(c,dk),r=rows(dk),e=r[0],w='日月火水木金土'[new Date(y,mo-1,d,12).getDay()];h+=`<tr class="valid-day ${dk===today()?'today-row':''}" data-day="${dk}"><td>${d}</td><td>${w}</td><td>${e?.start||'—'}</td><td>${e?.end||'—'}</td><td>${a?fmtMinutes(a.work):'—'}</td><td>${a?fmtMinutes(a.ot):'—'}</td><td>${a?fmtMinutes(a.deep):'—'}</td><td>${a?.holiday?'法定休日':a?'勤務':'—'}</td></tr>`}$('#dailyRows').innerHTML=h;$$('[data-day]').forEach(r=>r.onclick=()=>editDay(r.dataset.day));$('#avgList').innerHTML=st.averages.map(a=>`<div class="kpi"><span class="label">${a.n}か月平均</span><strong>${fmtMinutes(a.minutes)}</strong></div>`).join('')||'<div class="help">前月データ不足</div>';$('#statusSummary').innerHTML=st.breaches.length?'<strong>要確認</strong><br>'+st.breaches.join('<br>'):`<strong>上限抵触を検出していません。</strong><br>残り目安 ${fmtMinutes(st.tightest.minutes)}（${st.tightest.label}）`;$('#monthRows').innerHTML=st.monthly.map(x=>`<tr><td>${x.key}</td><td>${fmtMinutes(x.ot)}</td><td>${fmtMinutes(x.holiday)}</td><td>${fmtMinutes(x.combined)}</td><td>${fmtMinutes(x.deepOT)}</td><td>${x.ot>45*60?'45h超':'—'}</td></tr>`).join('')}
function editDay(d){selected=d;let e=rows(d).at(-1);$('#detailDate').value=d;$('#detailWorkType').value=e?.isLegalHoliday?'legalHoliday':'normal';$('#detailStart').value=e?.start||'';$('#detailEnd').value=e?.end||'';$('#detailBreakMinutes').value=e?.breakMinutes??0;$('#detailNightBreak').value=e?.nightBreakMinutes??0;$('#detailMemo').value=e?.memo||'';updateBreak(false);$('#detailTitle').textContent=fmtDate(d)+' の勤務詳細';$('#dayDetailCard').classList.remove('hidden');setTimeout(()=>$('#dayDetailCard').scrollIntoView({behavior:'smooth'}),0)}
function updateBreak(overwrite=true){let s=$('#detailStart').value,e=$('#detailEnd').value;if(!s||!e){$('#detailCompanyBreak').value=$('#detailStatutoryBreak').value=0;return}let c=companyBreakSuggestionMinutes(s,e);$('#detailCompanyBreak').value=c;$('#detailStatutoryBreak').value=statutoryBreakSuggestionMinutes(s,e);if(overwrite)$('#detailBreakMinutes').value=c}
async function saveDay(ev){ev.preventDefault();let d=$('#detailDate').value,e=rows(d).at(-1),n=new Date().toISOString();if(!e){e={id:uid(),date:d,createdAt:n};entries.push(e)}Object.assign(e,{start:$('#detailStart').value,end:$('#detailEnd').value,breakMinutes:+$('#detailBreakMinutes').value||0,nightBreakMinutes:+$('#detailNightBreak').value||0,isLegalHoliday:$('#detailWorkType').value==='legalHoliday',memo:$('#detailMemo').value.trim(),updatedAt:n});await put('entries',e);render();editDay(d)}
async function deleteDay(){let r=rows($('#detailDate').value);if(!r.length||!confirm('この日の勤務データを削除しますか？'))return;for(let e of r)await del('entries',e.id);entries=entries.filter(e=>!r.includes(e));$('#dayDetailCard').classList.add('hidden');render()}
function renderWage(){let k=$('#wageMonth').value||curMonth(),m=sumMonth(classified(),k),w=wageEstimate(m,settings);$('#hourly').textContent=yen(w.hourly);$('#wageTotal').textContent=yen(w.total);$('#premiumOnly').textContent=yen(w.premiumOnly);$('#wageBreakdown').innerHTML=`時間外60h以下：<b>${w.ot60.toFixed(2)}h</b> ×125%<br>60h超：<b>${w.otOver.toFixed(2)}h</b> ×150%<br>深夜時間外：<b>${(m.deepOT/60).toFixed(2)}h</b> +25%<br>法定休日：<b>${(m.holiday/60).toFixed(2)}h</b> ×135%<br>法定休日深夜：<b>${(m.holidayDeep/60).toFixed(2)}h</b> +25%<br>所定内深夜：<b>${(m.scheduledDeep/60).toFixed(2)}h</b> +25%`;let a=payslips[k]?.actualAllowance??'';$('#actualAllowance').value=a;$('#allowanceDiff').value=a===''?'':yen(+a-w.total);let rr=classified().filter(r=>r.date.startsWith(k));$('#correctionRows').innerHTML=rr.map(r=>`<tr><td>${r.date}</td>${['overtimeMinutes','deepOvertimeMinutes','legalHolidayMinutes','legalHolidayDeepMinutes','scheduledDeepMinutes'].map(q=>`<td><input class="miniinput" data-id="${r.id}" data-key="${q}" type="number" value="${Math.round(r.override?.[q]??r.calc[q]??0)}"></td>`).join('')}<td><button class="linkbtn" data-save="${r.id}">保存</button></td></tr>`).join('')||'<tr><td colspan="7">データなし</td></tr>';$$('[data-save]').forEach(b=>b.onclick=()=>saveCorr(b.dataset.save))}
async function saveCorr(id){let e=entries.find(x=>x.id===id),o={};$$(`[data-id="${id}"]`).forEach(i=>o[i.dataset.key]=Math.max(0,+i.value||0));e.override=o;await put('entries',e);render()}
function renderSettings(){for(let k of['baseSalary','wageBaseMonthly','avgMonthlyScheduledHours','dailyLegalHours','weeklyLegalHours','agreementStartMonth'])$('#'+k).value=settings[k]??'';$('#weekStartsMonday').checked=settings.weekStartsMonday!==false;$('#disasterRestoration').checked=!!settings.disasterRestoration;checkPersist()}
async function saveSettings(){settings={...settings,baseSalary:+$('#baseSalary').value||0,wageBaseMonthly:+$('#wageBaseMonthly').value||0,avgMonthlyScheduledHours:+$('#avgMonthlyScheduledHours').value||160,dailyLegalHours:+$('#dailyLegalHours').value||8,weeklyLegalHours:+$('#weeklyLegalHours').value||40,agreementStartMonth:+$('#agreementStartMonth').value||4,weekStartsMonday:$('#weekStartsMonday').checked,disasterRestoration:$('#disasterRestoration').checked};await put('settings',{key:'main',value:settings});render()}
async function checkPersist(){let e=$('#storageState');if(!navigator.storage?.persisted)return e.textContent='永続保存API非対応';let p=await navigator.storage.persisted();e.textContent=p?'永続保存：有効':'永続保存：未確定';e.className='status '+(p?'ok':'warn')}
async function persist(){let ok=await navigator.storage?.persist?.();await checkPersist();alert(ok?'永続ストレージが有効です。':'永続化は保証されません。')}
function b64(b){let s='';b.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function key(p,s){let b=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:150000,hash:'SHA-256'},b,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function backup(){let payload={app:'zangyo36',version:2,exportedAt:new Date().toISOString(),entries,settings,payslips},p=$('#backupPassword').value,blob,name;if(p){let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(p,salt),enc=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(JSON.stringify(payload)));blob=new Blob([JSON.stringify({format:'zangyo36-aesgcm-v1',salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(enc))})]);name=`zangyo36_${today()}.zgbak`}else{if(!confirm('暗号化せず保存しますか？'))return;blob=new Blob([JSON.stringify(payload)]);name=`zangyo36_${today()}.json`}let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function restore(f){try{let o=JSON.parse(await f.text());if(o.format==='zangyo36-aesgcm-v1'){let p=$('#backupPassword').value||prompt('パスワード');if(!p)return;let k=await key(p,unb64(o.salt)),d=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(o.iv)},k,unb64(o.data));o=JSON.parse(new TextDecoder().decode(d))}if(o.app!=='zangyo36'||!confirm('現在データを置換しますか？'))return;await clear('entries');await clear('payslips');for(let e of o.entries||[])await put('entries',e);for(let [m,p]of Object.entries(o.payslips||{}))await put('payslips',{month:m,...p});settings={...DEF,...o.settings};await put('settings',{key:'main',value:settings});await load();render();alert('復元しました。')}catch(e){alert('復元できませんでした。')}}
async function load(){entries=await all('entries');let s=await all('settings');settings={...DEF,...(s.find(x=>x.key==='main')?.value||{})};let p=await all('payslips');payslips=Object.fromEntries(p.map(x=>[x.month,x]))}
function render(){renderToday();renderMonth();renderWage();renderSettings()}
function bind(){$$('.tabbtn').forEach(b=>b.onclick=()=>tab(b.dataset.tab));hold($('#clockInBtn'),'in');hold($('#clockOutBtn'),'out');$('#editToday').onclick=()=>{$('#monthlyMonth').value=curMonth();tab('monthly');editDay(today())};$('#monthlyMonth').onchange=renderMonth;$('#dayDetailForm').onsubmit=saveDay;$('#detailStart').onchange=$('#detailEnd').onchange=()=>updateBreak(true);$('#deleteDay').onclick=deleteDay;$('#closeDetail').onclick=()=>$('#dayDetailCard').classList.add('hidden');$('#wageMonth').onchange=renderWage;$('#saveSettings').onclick=saveSettings;$('#requestPersist').onclick=persist;$('#actualAllowance').oninput=()=>{let k=$('#wageMonth').value,w=wageEstimate(sumMonth(classified(),k),settings),v=$('#actualAllowance').value;$('#allowanceDiff').value=v===''?'':yen(+v-w.total)};$('#savePayslip').onclick=async()=>{let month=$('#wageMonth').value,actualAllowance=+$('#actualAllowance').value||0;await put('payslips',{month,actualAllowance});payslips[month]={month,actualAllowance};renderWage()};$('#exportBackup').onclick=backup;$('#importBackup').onchange=e=>{let f=e.target.files?.[0];if(f)restore(f);e.target.value=''};$('#clearAll').onclick=async()=>{if(confirm('勤務・給与照合データを全削除しますか？')){await clear('entries');await clear('payslips');entries=[];payslips={};render()}}}
async function init(){initOpts();db=await openDB();await load();bind();clock();setInterval(clock,1000);render();tab('today');if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}}
init().catch(e=>{console.error(e);alert('初期化に失敗しました。')});
